### ISSUE TITLE
How to/can you creat a example for writing of a array of data?

### ISSUE THREAD

**Issue by Steem147** [danesparza/InfluxClient#13]
I'm trying to send around a 1000 tags to Influx and there for i would like to write them as a array.
this would be needed for speed optimization.

**Comment by danesparza** [comment]
I'm confused.  Do you mean 1000 tags for a single measurement?  Or 1000 measurements?  The client should support either case -- [and this unit test is already written](https://github.com/danesparza/InfluxClient/blob/master/InfluxClient.Tests/ManagerTests.cs#L134-L176) (and shows what you're asking).

**Comment by Steem147** [comment]
I meant 1000 fields :) But the example you provide is the one i was looking for. couldn't find it.
Thanks in advance.
