### ISSUE TITLE
Ability to specify Action for logging errors

### ISSUE THREAD

**Issue by andymac4182** [danesparza/InfluxClient#2]
What do you think of the idea of being able to supply an Action that will log the errors to the logging framework the end developer is using without throwing the error. This would be ideal for the apps I work on so I can see the errors without having an error from InfluxClient bubbling up to my app. 

The Action would take 2 parameters exception and message. This idea came from how https://github.com/uglybugger/NotDeadYet/blob/63eebdf883020896efcefee9c4209ae22b4850c9/src/NotDeadYet/Configuration/HealthCheckerConfiguration.cs#L9 handles logging. 

I would be happy to look at implementing this if you liked the idea.

**Comment by danesparza** [comment]
@andymac4182 I struggled with how to provide the information devs needed without pummeling them with errors.  I think the example you provide is a good one -- I like it.  Go ahead and create it and I'll review it.  Thanks!

**Comment by andymac4182** [comment]
Closing off as conversation is on #3
